export class OrderDetailDto{
    orderDetailId:number;
    orderId:number;
    createDate:string;
    updateDate:string;
    orderStatus:string;
    orderDelivery:string;
    orderPayment:string;
    productId:number;
    productName:string;
    size:string;
    color:string;
    userId:number;
    userName:string;
    addressUser:string;
    phoneNumber:string;
    email:string;
    quantity:number;
    price:number;
    constructor(){
        this.addressUser='';
        this.color='';
        this.createDate='';
        this.email='';
        this.orderDelivery='';
        this.orderDetailId=0;
        this.orderId=0;
        this.orderId=0;
        this.orderPayment='';
        this.orderStatus='';
        this.phoneNumber='';
        this.productId=0;
        this.productName='';
        this.size='';
        this.updateDate='';
        this.userId=0;
        this.userName='';
        this.quantity=0;
        this.price=0;
    }
}